# =============================================================================
# AI-GENERATED CODE
# Generated by: Claude (Anthropic), claude-sonnet-4-6
# Date: April 2026
# Prompt context: GAE computation for PPO on continuous control task
# Modified by: Victoria Feng — verified against GAE paper (Schulman et al. 2016)
# =============================================================================

import torch


def compute_gae(rewards, values, dones, gamma=0.99, gae_lambda=0.95):
    """
    Computes Generalized Advantage Estimation (GAE).
    
    Reference: Schulman et al., "High-Dimensional Continuous Control Using
    Generalized Advantage Estimation" (2016). https://arxiv.org/abs/1506.02438

    Args:
        rewards: list of rewards from rollout
        values:  list of value estimates from critic
        dones:   list of episode termination flags
        gamma:       discount factor
        gae_lambda:  GAE smoothing parameter (bias-variance tradeoff)

    Returns:
        advantages: normalized advantage estimates
        returns:    target returns for value function update

    # AI-GENERATED: Full function logic generated by Claude.
    """

    # AI-GENERATED: Reverse iteration over timesteps to compute GAE recursively
    advantages = []
    gae = 0

    for t in reversed(range(len(rewards))):
        # Bootstrap from next value, except at terminal states
        next_value = 0 if t == len(rewards) - 1 else values[t + 1]

        # AI-GENERATED: TD residual (delta) + discounted GAE accumulation
        delta = rewards[t] + gamma * next_value * (1 - dones[t]) - values[t]
        gae = delta + gamma * gae_lambda * (1 - dones[t]) * gae
        advantages.insert(0, gae)

    advantages = torch.FloatTensor(advantages)
    returns = advantages + torch.FloatTensor(values)

    # AI-GENERATED: Normalize advantages for training stability
    advantages = (advantages - advantages.mean()) / (advantages.std() + 1e-8)

    return advantages, returns