# =============================================================================
# AI-GENERATED CODE
# Generated by: Claude (Anthropic), claude-sonnet-4-6
# Date: April 2026
# Prompt context: Custom reward shaping wrapper for InvertedPendulum-v5
# Modified by: Victoria Feng
# =============================================================================

import gymnasium as gym
import numpy as np


class CustomPendulumEnv(gym.Wrapper):
    """
    Custom reward shaping wrapper for InvertedPendulum-v5.

    Modifies the base reward function by adding:
        1. Action penalty     — discourages large control inputs (energy efficiency)
        2. Position penalty   — discourages drifting far from center (stability)

    Base reward: +1 per timestep the pendulum stays balanced (survival reward)

    Modified reward:
        r = 1 - action_penalty * ||action||^2 - position_penalty * |x_position|

    Design justification:
        - Action penalty encourages smooth, minimal control effort
        - Position penalty encourages the cart to stay near the center of the track
        - Both terms are small (0.01) to avoid overwhelming the survival signal

    # AI-GENERATED: Full class structure and reward terms generated by Claude.
    # Reward term coefficients selected and justified by [Your Name].
    """

    def __init__(self, env, action_penalty=0.01, position_penalty=0.01):
        """
        Args:
            env:              base gymnasium environment
            action_penalty:   coefficient penalizing large actions
            position_penalty: coefficient penalizing distance from center
        
        # AI-GENERATED: __init__ generated by Claude.
        """
        super().__init__(env)
        self.action_penalty = action_penalty
        self.position_penalty = position_penalty

    def step(self, action):
        """
        Step the environment and apply custom reward shaping.

        Observation space for InvertedPendulum-v5:
            obs[0] = x position of cart
            obs[1] = sine of pole angle
            obs[2] = cosine of pole angle
            obs[3] = velocity of cart

        # AI-GENERATED: Step logic and observation indexing generated by Claude.
        """
        obs, reward, terminated, truncated, info = self.env.step(action)

        # Penalty for large control inputs (encourages energy efficiency)
        action_pen = self.action_penalty * np.sum(action ** 2)

        # Penalty for cart drifting far from center
        x_position = obs[0]
        position_pen = self.position_penalty * abs(x_position)

        # Modified reward
        custom_reward = reward - action_pen - position_pen

        # Store reward components in info for debugging/logging
        info["base_reward"] = reward
        info["action_penalty"] = action_pen
        info["position_penalty"] = position_pen
        info["custom_reward"] = custom_reward

        return obs, custom_reward, terminated, truncated, info


def make_custom_env(action_penalty=0.01, position_penalty=0.01, seed=42):
    """
    Factory function to create a wrapped CustomPendulumEnv.

    Args:
        action_penalty:   coefficient penalizing large actions
        position_penalty: coefficient penalizing distance from center
        seed:             random seed

    Returns:
        wrapped gymnasium environment

    # AI-GENERATED: Factory function generated by Claude.
    """
    env = gym.make("InvertedPendulum-v5")
    env = CustomPendulumEnv(
        env,
        action_penalty=action_penalty,
        position_penalty=position_penalty
    )
    return env


if __name__ == "__main__":
    # Quick sanity check — verify wrapper works and reward components are logged
    # AI-GENERATED: Sanity check generated by Claude.
    env = make_custom_env()
    obs, _ = env.reset(seed=42)

    total_base_reward = 0
    total_custom_reward = 0
    done = False

    while not done:
        action = env.action_space.sample()
        obs, reward, terminated, truncated, info = env.step(action)
        done = terminated or truncated

        total_base_reward += info["base_reward"]
        total_custom_reward += info["custom_reward"]

    print(f"Base reward:   {total_base_reward:.2f}")
    print(f"Custom reward: {total_custom_reward:.2f}")
    print(f"Difference:    {total_base_reward - total_custom_reward:.2f}")
    env.close()