# =============================================================================
# AI-GENERATED CODE
# Generated by: Claude (Anthropic), claude-sonnet-4-6
# Date: April 2026
# Prompt context: Evaluation script for trained PPO agent on InvertedPendulum-v5
#                 with checkpoint loading and video recording
# Modified by: Victoria Feng
# =============================================================================

import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

import torch
import numpy as np
import gymnasium as gym
import glob
import argparse
import os
from pyvirtualdisplay import Display
from IPython.display import HTML
from datetime import datetime
from base64 import b64encode
from models.actor_critic import ActorCritic

# --- Config ---
ENV_NAME = "InvertedPendulum-v5"
HIDDEN_DIM = 64
CHECKPOINT_PATH = "/content/drive/MyDrive/cs372_final_project/checkpoints"
VIDEO_PATH = "/content/drive/MyDrive/cs372_final_project/videos"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
SEED = 2026


def load_model(checkpoint_path, obs_dim, act_dim, hidden_dim, device):
    """
    Load a trained ActorCritic model from a checkpoint file.

    Args:
        checkpoint_path: path to .pt checkpoint file
        obs_dim:         observation space dimension
        act_dim:         action space dimension
        hidden_dim:      hidden layer dimension (must match checkpoint)
        device:          torch device

    # AI-GENERATED: Full function generated by Claude.
    """
    model = ActorCritic(obs_dim, act_dim, hidden_dim).to(device)
    model.load_state_dict(torch.load(checkpoint_path, map_location=device))
    model.eval()
    print(f"Loaded checkpoint: {checkpoint_path}")
    return model


def get_latest_checkpoint(checkpoint_dir):
    """
    Automatically find the latest checkpoint in a directory.

    # AI-GENERATED: Full function generated by Claude.
    """
    checkpoints = glob.glob(os.path.join(checkpoint_dir, "ppo_update_*.pt"))
    if not checkpoints:
        raise FileNotFoundError(f"No checkpoints found in {checkpoint_dir}")
    
    # Sort by update number
    checkpoints.sort(key=lambda x: int(x.split("_")[-1].replace(".pt", "")))
    latest = checkpoints[-1]
    print(f"Found {len(checkpoints)} checkpoints. Using latest: {latest}")
    return latest


def evaluate(model, env_name, n_episodes=100, seed=42, device="cpu"):
    """
    Evaluate a trained model over n_episodes and report statistics.

    Args:
        model:      trained ActorCritic model
        env_name:   gymnasium environment name
        n_episodes: number of episodes to evaluate over
        seed:       random seed
        device:     torch device

    Returns:
        dict of evaluation statistics

    # AI-GENERATED: Full function generated by Claude.
    """
    env = gym.make(env_name)
    rewards = []
    episode_lengths = []

    for episode in range(n_episodes):
        obs, _ = env.reset(seed=seed + episode)  # different seed each episode
        total_reward = 0
        episode_length = 0
        done = False

        while not done:
            obs_tensor = torch.FloatTensor(obs).unsqueeze(0).to(device)
            with torch.no_grad():
                action, _, _ = model.get_action(obs_tensor)
            obs, reward, terminated, truncated, _ = env.step(
                action.cpu().numpy()[0]
            )
            done = terminated or truncated
            total_reward += reward
            episode_length += 1

        rewards.append(total_reward)
        episode_lengths.append(episode_length)

    env.close()

    stats = {
        "mean_reward":       np.mean(rewards),
        "std_reward":        np.std(rewards),
        "min_reward":        np.min(rewards),
        "max_reward":        np.max(rewards),
        "median_reward":     np.median(rewards),
        "mean_ep_length":    np.mean(episode_lengths),
        "success_rate":      np.mean([r >= 990 for r in rewards]),  # % episodes near perfect
        "n_episodes":        n_episodes
    }

    return stats, rewards


def print_stats(stats):
    """
    Print evaluation statistics in a readable format.

    # AI-GENERATED: Full function generated by Claude.
    """
    print("\n" + "="*50)
    print("EVALUATION RESULTS")
    print("="*50)
    print(f"Episodes:       {stats['n_episodes']}")
    print(f"Mean Reward:    {stats['mean_reward']:.2f}")
    print(f"Std Reward:     {stats['std_reward']:.2f}")
    print(f"Min Reward:     {stats['min_reward']:.2f}")
    print(f"Max Reward:     {stats['max_reward']:.2f}")
    print(f"Median Reward:  {stats['median_reward']:.2f}")
    print(f"Mean Ep Length: {stats['mean_ep_length']:.2f}")
    print(f"Success Rate:   {stats['success_rate']*100:.1f}%")
    print("="*50 + "\n")


def record_video(model, env_name, video_path, device, seed=42):
    """
    Record a video of the agent playing one episode.

    # AI-GENERATED: Full function generated by Claude.
    """
    
    # AI-GENERATED: Timestamped subfolder to prevent overwriting
    timestamped_path = os.path.join(
        video_path, 
        datetime.now().strftime("%Y%m%d_%H%M%S")
    )
    os.makedirs(timestamped_path, exist_ok=True)

    env = gym.make(env_name, render_mode="rgb_array")
    env = gym.wrappers.RecordVideo(
        env,
        video_folder=timestamped_path,
        episode_trigger=lambda e: True
    )

    obs, _ = env.reset(seed=seed)
    total_reward = 0
    done = False

    while not done:
        obs_tensor = torch.FloatTensor(obs).unsqueeze(0).to(device)
        with torch.no_grad():
            action, _, _ = model.get_action(obs_tensor)
        obs, reward, terminated, truncated, _ = env.step(
            action.cpu().numpy()[0]
        )
        done = terminated or truncated
        total_reward += reward

    env.close()
    print(f"Video saved to {video_path} | Episode reward: {total_reward:.2f}")
    return total_reward


def compare_checkpoints(checkpoint_dir, env_name, hidden_dim, device, n_episodes=20):
    """
    Evaluate multiple checkpoints and compare performance over training.
    Useful for generating learning progression data.

    # AI-GENERATED: Full function generated by Claude.
    """
    env = gym.make(env_name)
    obs_dim = env.observation_space.shape[0]
    act_dim = env.action_space.shape[0]
    env.close()

    checkpoints = sorted(
        glob.glob(os.path.join(checkpoint_dir, "ppo_update_*.pt")),
        key=lambda x: int(x.split("_")[-1].replace(".pt", ""))
    )

    if not checkpoints:
        raise FileNotFoundError(f"No checkpoints found in {checkpoint_dir}")

    print(f"\nComparing {len(checkpoints)} checkpoints...\n")
    results = []

    for ckpt in checkpoints:
        update_num = int(ckpt.split("_")[-1].replace(".pt", ""))
        model = load_model(ckpt, obs_dim, act_dim, hidden_dim, device)
        stats, _ = evaluate(model, env_name, n_episodes=n_episodes, device=device)
        results.append({
            "update": update_num,
            "mean_reward": stats["mean_reward"],
            "std_reward": stats["std_reward"]
        })
        print(f"Update {update_num:4d} | "
              f"Mean Reward: {stats['mean_reward']:8.2f} | "
              f"Std: {stats['std_reward']:6.2f}")

    return results


# --- Main ---
if __name__ == "__main__":
    # AI-GENERATED: Argument parsing for flexible checkpoint selection
    parser = argparse.ArgumentParser(description="Evaluate trained PPO agent")
    parser.add_argument("--checkpoint", type=str, default=None,
                        help="Path to checkpoint file. If not provided, uses latest.")
    parser.add_argument("--n_episodes", type=int, default=100,
                        help="Number of evaluation episodes")
    parser.add_argument("--record", action="store_true",
                        help="Record a video of the agent")
    parser.add_argument("--compare", action="store_true",
                        help="Compare all checkpoints")
    args = parser.parse_args()

    # Setup environment dimensions
    env = gym.make(ENV_NAME)
    obs_dim = env.observation_space.shape[0]
    act_dim = env.action_space.shape[0]
    env.close()

    if args.compare:
        # Compare all checkpoints
        compare_checkpoints(CHECKPOINT_PATH, ENV_NAME, HIDDEN_DIM, DEVICE)

    else:
        # Load specific or latest checkpoint
        checkpoint = args.checkpoint or get_latest_checkpoint(CHECKPOINT_PATH)
        model = load_model(checkpoint, obs_dim, act_dim, HIDDEN_DIM, DEVICE)

        # Evaluate
        stats, rewards = evaluate(
            model, ENV_NAME,
            n_episodes=args.n_episodes,
            seed=SEED,
            device=DEVICE
        )
        print_stats(stats)

        # Record video if requested
        if args.record:
            record_video(model, ENV_NAME, VIDEO_PATH, DEVICE, seed=SEED)