# =============================================================================
# AI-GENERATED CODE
# Generated by: Claude (Anthropic), claude-sonnet-4-6
# Date: April 2026
# Prompt context: GAE computation and PPO update loop for PPO on continuous control task. 
# Modified by: Victoria Feng — verified against GAE paper (Schulman et al. 2016)
# =============================================================================

import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from sqlalchemy import values
import torch
import torch.nn as nn
import torch.optim as optim
from src.rollout_buffer import RolloutBuffer


def compute_gae(rewards, values, dones, gamma=0.99, gae_lambda=0.95):
    """
    Computes Generalized Advantage Estimation (GAE).
    
    Reference: Schulman et al., "High-Dimensional Continuous Control Using
    Generalized Advantage Estimation" (2016). https://arxiv.org/abs/1506.02438

    Args:
        rewards: list of rewards from rollout
        values:  list of value estimates from critic
        dones:   list of episode termination flags
        gamma:       discount factor
        gae_lambda:  GAE smoothing parameter (bias-variance tradeoff)

    Returns:
        advantages: normalized advantage estimates
        returns:    target returns for value function update

    # AI-GENERATED: Full function logic generated by Claude.
    """

    # AI-GENERATED: Reverse iteration over timesteps to compute GAE recursively
    advantages = []
    gae = 0

    for t in reversed(range(len(rewards))):
        # Bootstrap from next value, except at terminal states
        next_value = 0 if t == len(rewards) - 1 else values[t + 1]

        # AI-GENERATED: TD residual (delta) + discounted GAE accumulation
        delta = rewards[t] + gamma * next_value * (1 - dones[t]) - values[t]
        gae = delta + gamma * gae_lambda * (1 - dones[t]) * gae
        advantages.insert(0, gae)

    advantages = torch.FloatTensor(advantages)
    returns = advantages + torch.FloatTensor(values)

    # AI-GENERATED: Normalize advantages for training stability
    advantages = (advantages - advantages.mean()) / (advantages.std() + 1e-8)

    return advantages, returns


class PPO:
    """
    Proximal Policy Optimization for continuous action spaces.
    
    Reference: Schulman et al., "Proximal Policy Optimization Algorithms" (2017)
    https://arxiv.org/abs/1707.06347
    
    # AI-GENERATED: Full class generated by Claude.
    """

    def __init__(
        self,
        model,
        lr=3e-4,
        gamma=0.99,
        gae_lambda=0.95,
        clip_eps=0.2,
        entropy_coef=0.01,
        value_coef=0.5,
        max_grad_norm=0.5,
        n_epochs=10,
        batch_size=64,
        device="cpu"
    ):
        self.model = model.to(device)
        # self.optimizer = optim.Adam(model.parameters(), lr=lr)
        self.optimizer = optim.Adam(model.parameters(), lr=lr)
        self.buffer = RolloutBuffer()

        # Hyperparameters
        self.gamma = gamma
        self.gae_lambda = gae_lambda
        self.clip_eps = clip_eps
        self.entropy_coef = entropy_coef
        self.value_coef = value_coef
        self.max_grad_norm = max_grad_norm
        self.n_epochs = n_epochs
        self.batch_size = batch_size
        self.device = device

    def select_action(self, obs):
        # AI-GENERATED: Convert obs to tensor, sample action from policy
        obs_tensor = torch.FloatTensor(obs).unsqueeze(0).to(self.device)
        with torch.no_grad():
            action, log_prob, value = self.model.get_action(obs_tensor)
        return (
            action.cpu().numpy()[0],
            log_prob.cpu().item(),
            value.cpu().item()
        )

    def update(self):
        # AI-GENERATED: Full PPO update step
        obs, actions, old_log_probs, rewards, values, dones = self.buffer.get()
        obs = obs.to(self.device)
        actions = actions.to(self.device)
        old_log_probs = old_log_probs.to(self.device)

        # Compute GAE advantages and returns
        advantages, returns = compute_gae(
            rewards.numpy(),
            values.numpy(),
            dones.numpy(),
            self.gamma,
            self.gae_lambda
        )
        advantages = advantages.to(self.device)
        returns = returns.to(self.device)

        # PPO update for n_epochs
        for _ in range(self.n_epochs):
            # Shuffle indices for minibatch updates
            indices = torch.randperm(len(obs))

            for start in range(0, len(obs), self.batch_size):
                batch_idx = indices[start:start + self.batch_size]

                batch_obs = obs[batch_idx]
                batch_actions = actions[batch_idx]
                batch_old_log_probs = old_log_probs[batch_idx]
                batch_advantages = advantages[batch_idx]
                batch_returns = returns[batch_idx]

                # Evaluate current policy on batch
                log_probs, values_pred, entropy = self.model.evaluate(
                    batch_obs, batch_actions
                )
                values_pred = values_pred.squeeze()

                # PPO clipped objective
                # AI-GENERATED: Ratio and clipping logic from Schulman et al. 2017
                ratio = (log_probs - batch_old_log_probs).exp()
                surr1 = ratio * batch_advantages
                surr2 = torch.clamp(ratio, 1 - self.clip_eps, 1 + self.clip_eps) * batch_advantages
                policy_loss = -torch.min(surr1, surr2).mean()

                # Value function loss
                value_loss = nn.MSELoss()(values_pred, batch_returns)

                # Entropy bonus (encourages exploration)
                entropy_loss = -entropy.mean()

                # Combined loss
                loss = policy_loss + self.value_coef * value_loss + self.entropy_coef * entropy_loss

                # Gradient update with clipping
                self.optimizer.zero_grad()
                loss.backward()
                nn.utils.clip_grad_norm_(self.model.parameters(), self.max_grad_norm)
                self.optimizer.step()

        self.buffer.clear()

        return {
            "policy_loss": policy_loss.item(),
            "value_loss": value_loss.item(),
            "entropy": -entropy_loss.item()
        }