# =============================================================================
# AI-GENERATED CODE
# Generated by: Claude (Anthropic), claude-sonnet-4-6
# Date: April 2026
# Prompt context: Standalone robustness evaluation script for trained PPO
#                 agent on InvertedPendulum-v5 via initial observation
#                 perturbation.
# Modified by: Victoria Feng
# =============================================================================

import torch
import numpy as np
import gymnasium as gym
import matplotlib.pyplot as plt
import argparse
import os

from models.actor_critic import ActorCritic
from evaluate import load_model, get_latest_checkpoint

# --- Config ---
ENV_NAME = "InvertedPendulum-v5"
HIDDEN_DIM = 64
CHECKPOINT_PATH = "/content/drive/MyDrive/cs372_project/checkpoints"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"


def evaluate_with_perturbation(model, perturbation_scale, n_episodes=50, device="cpu"):
    """
    Evaluate agent robustness by adding Gaussian noise to the initial
    observation after environment reset. Simulates harder starting conditions
    than the default environment reset provides.

    Args:
        model:              trained ActorCritic model
        perturbation_scale: standard deviation of Gaussian noise added to obs
        n_episodes:         number of episodes to evaluate over
        device:             torch device

    Returns:
        mean_reward: mean total reward across episodes
        std_reward:  standard deviation of total reward across episodes

    # AI-GENERATED: Full function generated by Claude.
    """
    env = gym.make(ENV_NAME)
    rewards = []

    for episode in range(n_episodes):
        obs, _ = env.reset(seed=episode)

        # AI-GENERATED: Gaussian noise perturbation to initial observation
        obs = obs + np.random.normal(0, perturbation_scale, size=obs.shape)
        obs = obs.astype(np.float32)

        total_reward = 0
        done = False

        while not done:
            obs_tensor = torch.FloatTensor(obs).unsqueeze(0).to(device)
            with torch.no_grad():
                action, _, _ = model.get_action(obs_tensor)
            obs, reward, terminated, truncated, _ = env.step(
                action.cpu().numpy()[0]
            )
            done = terminated or truncated
            total_reward += reward

        rewards.append(total_reward)

    env.close()
    return np.mean(rewards), np.std(rewards)


def run_robustness_evaluation(
    model,
    perturbation_scales=None,
    n_episodes=50,
    device="cpu",
    save_plot=True
):
    """
    Run robustness evaluation across a range of perturbation scales,
    print a summary table, and optionally save a plot.

    Args:
        model:               trained ActorCritic model
        perturbation_scales: list of noise std values to test
        n_episodes:          number of episodes per perturbation scale
        device:              torch device
        save_plot:           whether to save the plot to plots/

    Returns:
        results: list of dicts with scale, mean_reward, std_reward

    # AI-GENERATED: Full function generated by Claude.
    """
    if perturbation_scales is None:
        perturbation_scales = [0.0, 0.05, 0.1, 0.2, 0.5, 1.0]

    os.makedirs("plots", exist_ok=True)

    mean_rewards = []
    std_rewards = []
    results = []

    print("Running robustness evaluation...")
    print(f"  Episodes per scale: {n_episodes}")
    print(f"  Perturbation scales: {perturbation_scales}\n")

    for scale in perturbation_scales:
        mean, std = evaluate_with_perturbation(
            model, scale, n_episodes=n_episodes, device=device
        )
        mean_rewards.append(mean)
        std_rewards.append(std)
        results.append({
            "scale": scale,
            "mean_reward": mean,
            "std_reward": std
        })
        print(f"  Scale {scale:.2f} | Mean: {mean:.2f} | Std: {std:.2f}")

    # --- Summary table ---
    # AI-GENERATED: Summary table generated by Claude.
    print("\n" + "=" * 55)
    print("ROBUSTNESS SUMMARY")
    print("=" * 55)
    print(f"{'Scale':<10} {'Mean Reward':<15} {'Std Reward':<15} {'vs Baseline'}")
    print("-" * 55)
    for r in results:
        vs_baseline = f"+{r['mean_reward'] - 4:.1f}" if r['mean_reward'] > 4 else f"{r['mean_reward'] - 4:.1f}"
        print(f"{r['scale']:<10.2f} {r['mean_reward']:<15.2f} {r['std_reward']:<15.2f} {vs_baseline}")
    print("=" * 55)

    # --- Plot ---
    # AI-GENERATED: Robustness curve plot generated by Claude.
    if save_plot:
        fig, ax = plt.subplots(figsize=(9, 5))

        ax.plot(
            perturbation_scales, mean_rewards,
            marker="o", color="blue", linewidth=2, label="Trained PPO Agent"
        )
        ax.fill_between(
            perturbation_scales,
            np.array(mean_rewards) - np.array(std_rewards),
            np.array(mean_rewards) + np.array(std_rewards),
            alpha=0.2, color="blue", label="±1 Std Dev"
        )
        ax.axhline(
            y=4, color="red", linestyle="--",
            linewidth=1.5, label="Random Baseline (~4)"
        )
        ax.axhline(
            y=1000, color="black", linestyle="--",
            linewidth=1.5, label="Maximum Possible (1000)"
        )

        ax.set_xlabel("Perturbation Scale (Gaussian noise std)")
        ax.set_ylabel("Mean Episode Reward")
        ax.set_title("Robustness to Initial State Perturbation — InvertedPendulum-v5")
        ax.legend()
        ax.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.savefig("plots/robustness_curve.png", dpi=150)
        plt.show()
        print("\nSaved: plots/robustness_curve.png")

    return results


# --- Main ---
if __name__ == "__main__":
    # AI-GENERATED: Argument parsing generated by Claude.
    parser = argparse.ArgumentParser(
        description="Evaluate trained PPO agent robustness to initial state perturbation"
    )
    parser.add_argument(
        "--checkpoint", type=str, default=None,
        help="Path to checkpoint file. If not provided, uses latest."
    )
    parser.add_argument(
        "--n_episodes", type=int, default=50,
        help="Number of episodes per perturbation scale"
    )
    parser.add_argument(
        "--scales", type=float, nargs="+",
        default=[0.0, 0.05, 0.1, 0.2, 0.5, 1.0],
        help="Perturbation scales to evaluate"
    )
    parser.add_argument(
        "--no_plot", action="store_true",
        help="Skip saving the plot"
    )
    args = parser.parse_args()

    # Load model
    env = gym.make(ENV_NAME)
    obs_dim = env.observation_space.shape[0]
    act_dim = env.action_space.shape[0]
    env.close()

    checkpoint = args.checkpoint or get_latest_checkpoint(CHECKPOINT_PATH)
    model = load_model(checkpoint, obs_dim, act_dim, HIDDEN_DIM, DEVICE)

    # Run evaluation
    run_robustness_evaluation(
        model=model,
        perturbation_scales=args.scales,
        n_episodes=args.n_episodes,
        device=DEVICE,
        save_plot=not args.no_plot
    )