# =============================================================================
# AI-GENERATED CODE
# Generated by: Claude (Anthropic), claude-sonnet-4-6
# Date: April 2026
# Prompt context: Rollout buffer for storing PPO trajectories
# Modified by: Victoria Feng — verified tensor shapes against environment dims
# =============================================================================

import torch
import numpy as np


class RolloutBuffer:
    """
    Stores a single rollout of experience for PPO updates.
    Cleared after each policy update.

    # AI-GENERATED: Full class structure generated by Claude.
    """

    def __init__(self):
        # AI-GENERATED: Simple list-based storage; converted to tensors in get()
        self.observations = []
        self.actions = []
        self.log_probs = []
        self.rewards = []
        self.values = []
        self.dones = []

    def store(self, obs, action, log_prob, reward, value, done):
        # AI-GENERATED: Append single timestep of experience
        self.observations.append(obs)
        self.actions.append(action)
        self.log_probs.append(log_prob)
        self.rewards.append(reward)
        self.values.append(value)
        self.dones.append(done)

    def clear(self):
        # AI-GENERATED: Reset buffer after PPO update
        self.__init__()

    def get(self):
        # AI-GENERATED: Convert stored lists to tensors for PPO update
        return (
            torch.FloatTensor(np.array(self.observations)),
            torch.FloatTensor(np.array(self.actions)),
            torch.FloatTensor(np.array(self.log_probs)),
            torch.FloatTensor(np.array(self.rewards)),
            torch.FloatTensor(np.array(self.values)),
            torch.FloatTensor(np.array(self.dones))
        )