# =============================================================================
# AI-GENERATED CODE
# Generated by: Claude (Anthropic), claude-sonnet-4-6
# Date: April 2026
# Prompt context: Main training loop for PPO on InvertedPendulum-v5
#                 with TensorBoard logging
# Modified by: Victoria Feng
# =============================================================================

import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

import torch
import numpy as np
import gymnasium as gym
from torch.utils.tensorboard import SummaryWriter
from models.actor_critic import ActorCritic
from src.ppo import PPO
from datetime import datetime

# --- Config ---
SEED = 2026
ENV_NAME = "InvertedPendulum-v5"
TOTAL_TIMESTEPS = 1_500_000
ROLLOUT_STEPS = 4096      
HIDDEN_DIM = 64
LR = 6e-4            
CLIP_EPS = 0.2
N_EPOCHS = 10           
BATCH_SIZE = 64
GAMMA = 0.99
GAE_LAMBDA = 0.95
ENTROPY_COEF = 0.01    # Decreased to encourage convergence
VALUE_COEF = 0.5       # Decrease to prevent value loss from dominating policy updates
MAX_GRAD_NORM = 0.5
LOG_INTERVAL = 5         # Log every N updates
SAVE_INTERVAL = 50        # Save checkpoint every N updates
CHECKPOINT_PATH = "/content/drive/MyDrive/cs372_final_project/checkpoints"
RUN_NAME = f"study_lr{LR}_valcoeff{VALUE_COEF}_clip{CLIP_EPS}_{datetime.now().strftime('%m%d%Y_%H%M%S')}"
RESUME_CHECKPOINT = f"{CHECKPOINT_PATH}/ppo_update_400.pt"

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {DEVICE}")

# --- Setup ---
torch.manual_seed(SEED)
np.random.seed(SEED)

env = gym.make(ENV_NAME)
obs, _ = env.reset(seed=SEED)
env.action_space.seed(SEED)

obs_dim = env.observation_space.shape[0]
act_dim = env.action_space.shape[0]

model = ActorCritic(obs_dim, act_dim, HIDDEN_DIM)
agent = PPO(
    model=model,
    lr=LR,
    gamma=GAMMA,
    gae_lambda=GAE_LAMBDA,
    clip_eps=CLIP_EPS,
    entropy_coef=ENTROPY_COEF,
    value_coef=VALUE_COEF,
    max_grad_norm=MAX_GRAD_NORM,
    n_epochs=N_EPOCHS,
    batch_size=BATCH_SIZE,
    device=DEVICE
)

# AI-GENERATED: Load checkpoint if specified
# if os.path.exists(RESUME_CHECKPOINT):
#     model.load_state_dict(torch.load(RESUME_CHECKPOINT, map_location=DEVICE))
#     print(f"Resumed from checkpoint: {RESUME_CHECKPOINT}")
# else:
#     print("No checkpoint found, starting fresh")

# AI-GENERATED: TensorBoard writer initialized with run name for experiment tracking
writer = SummaryWriter(
    log_dir=f"/content/drive/MyDrive/cs372_final_project/logs/{RUN_NAME}"
)

# --- Training ---
timestep = 0
update = 0
episode_rewards = []
current_episode_reward = 0

obs, _ = env.reset(seed=SEED)

while timestep < TOTAL_TIMESTEPS:

    # Collect rollout
    for _ in range(ROLLOUT_STEPS):
        action, log_prob, value = agent.select_action(obs)
        next_obs, reward, terminated, truncated, _ = env.step(action)
        done = terminated or truncated

        agent.buffer.store(obs, action, log_prob, reward, value, done)

        obs = next_obs
        current_episode_reward += reward
        timestep += 1

        if done:
            episode_rewards.append(current_episode_reward)
            current_episode_reward = 0
            obs, _ = env.reset()

    # PPO update
    losses = agent.update()
    update += 1

    # AI-GENERATED: Logging block with TensorBoard integration
    if update % LOG_INTERVAL == 0 and episode_rewards:
        mean_reward = np.mean(episode_rewards[-10:])

        # Console logging
        print(
            f"Update {update} | "
            f"Timestep {timestep} | "
            f"Mean Reward (last 10 eps): {mean_reward:.2f} | "
            f"Policy Loss: {losses['policy_loss']:.4f} | "
            f"Value Loss: {losses['value_loss']:.4f} | "
            f"Entropy: {losses['entropy']:.4f}"
        )

        # TensorBoard logging
        writer.add_scalar("reward/mean_reward", mean_reward, timestep)
        writer.add_scalar("losses/policy_loss", losses['policy_loss'], timestep)
        writer.add_scalar("losses/value_loss", losses['value_loss'], timestep)
        writer.add_scalar("losses/entropy", losses['entropy'], timestep)

    # # Checkpoint
    # if update % SAVE_INTERVAL == 0:
    #     torch.save(
    #         model.state_dict(),
    #         f"{CHECKPOINT_PATH}/ppo_update_{update}.pt"
    #     )
    #     print(f"Checkpoint saved at update {update}")

# Only for experiments
torch.save(
    model.state_dict(),
    f"{CHECKPOINT_PATH}/LR2_study_lr{LR}_valcoeff{VALUE_COEF}_clip{CLIP_EPS}.pt"
)
print(f"Checkpoint saved at final update")

env.close()
writer.close()
print("Training complete.")