# =============================================================================
# AI-GENERATED CODE
# Generated by: Claude (Anthropic), claude-sonnet-4-6
# Date: April 2026
# Prompt context: Actor-critic network for PPO on InvertedDoublePendulum-v5
# Modified by: Victoria Feng — verified dimensions, tested forward pass
# =============================================================================

import torch
import torch.nn as nn
from torch.distributions import Normal


class ActorCritic(nn.Module):
    """
    Shared-trunk actor-critic network for continuous action spaces.
    
    Architecture:
        - Shared MLP trunk with LayerNorm and Tanh activations
        - Actor head: outputs Gaussian policy (mu + learned log_std)
        - Critic head: outputs scalar state value
    
    # AI-GENERATED: Full class structure and forward pass logic generated by Claude.
    """

    def __init__(self, obs_dim, act_dim, hidden_dim=64):
        super().__init__()

        # AI-GENERATED: Shared trunk with LayerNorm for training stability
        self.shared = nn.Sequential(
            nn.Linear(obs_dim, hidden_dim),
            nn.LayerNorm(hidden_dim),
            nn.Tanh(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.LayerNorm(hidden_dim),
            nn.Tanh()
        )

        # AI-GENERATED: Policy head — outputs mean action; log_std is a
        # learned parameter independent of observation
        self.mu = nn.Linear(hidden_dim, act_dim)
        self.log_std = nn.Parameter(torch.zeros(act_dim))

        # AI-GENERATED: Value head — scalar estimate of state value V(s)
        self.value = nn.Linear(hidden_dim, 1)

    def forward(self, obs):
        # AI-GENERATED: Forward pass returning a Normal distribution and value
        x = self.shared(obs)
        mu = self.mu(x)
        std = self.log_std.exp()
        dist = Normal(mu, std)
        value = self.value(x)
        return dist, value

    def get_action(self, obs):
        # AI-GENERATED: Sample action, compute log probability and value
        # Used during rollout collection
        dist, value = self.forward(obs)
        action = dist.sample()
        log_prob = dist.log_prob(action).sum(-1)
        return action, log_prob, value

    def evaluate(self, obs, action):
        # AI-GENERATED: Recompute log_prob and entropy for a given (obs, action)
        # pair. Used during PPO update step.
        dist, value = self.forward(obs)
        log_prob = dist.log_prob(action).sum(-1)
        entropy = dist.entropy().sum(-1)
        return log_prob, value, entropy